server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Auth Service routes
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /api/auth/${segment}
        
        # User routes (Auth Service)
        - id: user-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /api/users/${segment}
            - AuthenticationFilter
        
        # Group routes (Auth Service)
        - id: group-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/groups/**
          filters:
            - RewritePath=/api/groups/(?<segment>.*), /api/groups/${segment}
            - AuthenticationFilter
        
        # Task Service routes
        - id: task-service
          uri: http://task-service:8082
          predicates:
            - Path=/api/tasks/**
          filters:
            - RewritePath=/api/tasks/(?<segment>.*), /api/tasks/${segment}
            - AuthenticationFilter
        
        # Daily Task routes (Task Service)
        - id: daily-task-service
          uri: http://task-service:8082
          predicates:
            - Path=/api/daily-tasks/**
          filters:
            - RewritePath=/api/daily-tasks/(?<segment>.*), /api/daily-tasks/${segment}
            - AuthenticationFilter
        
        # Report Service routes
        - id: report-service
          uri: http://report-service:8083
          predicates:
            - Path=/api/reports/**
          filters:
            - RewritePath=/api/reports/(?<segment>.*), /api/reports/${segment}
            - AuthenticationFilter

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://frontend:80"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            exposedHeaders:
              - Authorization

jwt:
  secret-key: 456126525254235874298574293579482375492835792347532

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,prometheus
  endpoint:
    gateway:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

